### ISSUE TITLE
Jaki byłby najmniejszy raytracer?

### ISSUE THREAD

**Issue by xor256** [marczych/RayTracer#5]
Szukam czegoś co pozwoli mi na narysowanie sceny bez kolorów.

**Comment by marczych** [comment]
Cześć,

nie mówią po polsku , więc mam zamiar odpowiedzieć w języku angielskim:

I'm not sure what exactly what you mean by "smallest raytracer", but this project can render spheres and triangles with a variety of textures. This definitely isn't a fully-featured scene renderer but rather a simple educational-focused raytracer that can be easily extended. Check out the homepage to see what it's capable of.

**Comment by xor256** [comment]
My english is horrible ;-(
 
I need information about all 'lines' and crossing point of scenes.
For example i have 2 triangles and one rectangles.
Is possible to get image with svg not raster image?
lines not pixels.
 
Thanks
Krzysztof
 
W dniu 2016-08-05 19:09:38 użytkownik Marc Zych <notifications@github.com> napisał:
Cześć,
nie mówią po polsku , więc mam zamiar odpowiedzieć w języku angielskim:
I'm not sure what exactly what you mean by "smallest raytracer", but this project can render spheres and triangles with a variety of textures. This definitely isn't a fully-featured scene renderer but rather a simple educational-focused raytracer that can be easily extended. Check out the homepage to see what it's capable of.

**Comment by marczych** [comment]
I don't think that it's possible with this raytracer. The output is a 2-dimensional array of colors rather than any vector-based format. You _might_ be able to take the resulting JPEG and convert it to an SVG but I don't know if that would work very well.
