### ISSUE TITLE
Just a simple question

### ISSUE THREAD

**Issue by Telokis** [marczych/RayTracer#7]
Hello,

I have a small question about your raytracer (that I love, wy the way)!
How does it handle color being more than 1.0 ? I see you are using the phong model so you do ambien + diffuse + specular + refractivereflective. Since that is only additions, how are you sure that this will never get above 1.0 for red, green and/or blue ?

I am working on a raytracer myself and I'm afraid of this exact point.

Thanks,
Telokis

**Comment by marczych** [comment]
It's been a while since I've worked on this project but it looks like there aren't any safeguards based on this: https://github.com/marczych/RayTracer/blob/a4c298f9e7725b94f5db2736518aff6baaaf1b8c/src/RayTracer.cpp#L147

Feel free to open a PR if you have a fix in mind!

**Comment by Telokis** [comment]
Thanks for your answers! I closed this issue because I found it here:
https://github.com/marczych/RayTracer/blob/a4c298f9e7725b94f5db2736518aff6baaaf1b8c/src/Image.cpp#L78

That's what I was looking for.
